const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function context(){const storage=new Map();const ctx=vm.createContext({console,TextEncoder,TextDecoder,crypto:require('node:crypto').webcrypto,sessionStorage:{getItem:()=>null,setItem(){}},localStorage:{setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},window:{addEventListener(){}},setTimeout,clearTimeout,queueMicrotask});vm.runInContext(fs.readFileSync('server/web/js/71-write.js','utf8'),ctx);vm.runInContext('writeStatus=()=>{};writeConflict=()=>{};writingUI.vaultID="fixture";',ctx);return {ctx,storage}}
test('save acknowledgement never marks subsequent typing as saved',async()=>{const {ctx,storage}=context();let finish;ctx.api=()=>new Promise(r=>{finish=r});vm.runInContext('writeFetch=api;var d={path:"draft.md",base:"base",revision:"r1",eol:"\\n",editor:{value:"submitted",text(){return this.value}}};var pending=writeSave(d);d.editor.value="newer typing";',ctx);finish({revision:'r2'});await ctx.pending;assert.equal(vm.runInContext('d.base',ctx),'submitted');assert.equal(vm.runInContext('d.revision',ctx),'r2');assert.equal(vm.runInContext('writeDirty(d)',ctx),true);assert.equal(JSON.parse([...storage.values()][0]).text,'newer typing')});
test('failed save retains original precondition and draft',async()=>{const {ctx,storage}=context();ctx.api=async()=>{const e=new Error('conflict');e.status=409;e.detail={raw:'external',revision:'r2'};throw e};vm.runInContext('writeFetch=api;var d={path:"draft.md",base:"base",revision:"r1",eol:"\\n",editor:{text(){return "mine"}}};var pending=writeSave(d);',ctx);assert.equal(await ctx.pending,false);assert.equal(vm.runInContext('d.revision',ctx),'r1');assert.equal(vm.runInContext('d.editor.text()',ctx),'mine');assert.equal(JSON.parse([...storage.values()][0]).text,'mine')});
test('anchors round trip CRLF and emoji; ambiguity is unanchored',()=>{const {ctx}=context();vm.runInContext('var raw="🌿\\r\\nselected words\\r\\nend";var d={base:raw,revision:"r1",eol:"\\r\\n",editor:{text(){return raw.replace(/\\r\\n/g,"\\n")}}};var a={revision:"r1",start:6,end:20,quote:"selected words",prefix:"🌿\\r\\n",suffix:"\\r\\nend"};',ctx);const range=vm.runInContext('writeLocate(d,a)',ctx);assert.equal(range.from,3);assert.equal(range.to,17);vm.runInContext('raw="same quote x same quote x";d.revision="r2";a={revision:"r1",quote:"quote",prefix:"same ",suffix:" x"};',ctx);assert.equal(vm.runInContext('writeLocate(d,a)',ctx),null)});
test('mixed line endings are detected rather than silently normalized',()=>{const {ctx}=context();assert.equal(vm.runInContext('writeEOL("a\\r\\nb\\nc").mixed',ctx),true);assert.equal(vm.runInContext('writeEOL("a\\r\\nb\\r\\n").mixed',ctx),false)});
function commentsContext(){const c=context();vm.runInContext('writeRenderComments=()=>{};writeMark=()=>{};showToast=()=>{};',c.ctx);return c}
test('comment acknowledgement preserves text typed during submission',async()=>{const {ctx}=commentsContext();let finish;ctx.api=()=>new Promise(r=>finish=r);vm.runInContext('writeFetch=api;var anchor={quote:"passage"};var d={path:"draft.md",comments:{revision:"r1"},pending:anchor,pendingBody:"submitted",commentRequest:0};var pending=writePost(d,{body:"submitted",anchor});d.pendingBody="newer thought";',ctx);finish({revision:'r2',threads:[{id:'thread'}]});await ctx.pending;assert.equal(vm.runInContext('d.pendingBody',ctx),'newer thought');assert.equal(vm.runInContext('d.pending===anchor',ctx),true);assert.equal(vm.runInContext('d.posting',ctx),false)});
test('successful reply clears only the submitted reply draft',async()=>{const {ctx}=commentsContext();ctx.api=async()=>({revision:'r2',threads:[]});vm.runInContext('writeFetch=api;var d={path:"draft.md",comments:{revision:"r1"},replyDrafts:{one:"reply",two:"keep"}};var pending=writePost(d,{thread:"one",body:"reply"});',ctx);await ctx.pending;assert.equal(vm.runInContext('d.replyDrafts.one',ctx),undefined);assert.equal(vm.runInContext('d.replyDrafts.two',ctx),'keep')});
test('late comment load cannot replace newer data or a moved file',async()=>{const {ctx}=commentsContext();const finish=[];ctx.api=()=>new Promise(r=>finish.push(r));vm.runInContext('writeFetch=api;var d={path:"old.md"};var first=writeLoadComments(d);var second=writeLoadComments(d);',ctx);finish[1]({document:{revision:'new'}});await ctx.second;finish[0]({document:{revision:'old'}});await ctx.first;assert.equal(vm.runInContext('d.comments.revision',ctx),'new');vm.runInContext('var third=writeLoadComments(d);d.path="moved.md";',ctx);finish[2]({document:{revision:'stale'}});await ctx.third;assert.equal(vm.runInContext('d.comments.revision',ctx),'new')});
test('empty selection clears the stale passage target',()=>{const {ctx}=commentsContext();vm.runInContext('writeRemember=()=>{};var d={selection:{from:1,to:4}};writingUI.active=d;writingUI.view={hidden:false};writingUI.selection={hidden:false};writeSelection(d,{empty:true});',ctx);assert.equal(vm.runInContext('d.selection',ctx),null);assert.equal(vm.runInContext('writingUI.selection.hidden',ctx),true)});
