package main

// Generated from the reviewed historic-rocks proposal (owner: accept, 2026-08-09).
// One entry per flagged item → the rock it belongs to. Consumed by overrideMap.
var overrides = []struct{ text, rock string }{
	{"Arrange a paid 1-3 day trial visit for Hasan in St. Louis (conditional on the brief)", "aion/team-building"},
	{"Source donated thymic tissue (email cardiothoracic surgeons / company Rhythmic) as backup model", "aion/thymus-program"},
	{"Get a cost estimate and hold a scoping conversation with Prof. Lee in China on the water-tank standing-wave device", "aion/ultrasound-platform"},
	{"Consider Robert Lufkin as CMO", "aion/team-building"},
	{"Send Sid the diligence portal and materials", "aion/series-a-15m"},
	{"Explore acquiring or winding down East America Science Co; informal right of first refusal to AION", "aion/partnerships-advisory"},
	{"Research alternative ways to stimulate thymic involution and present options this week", "aion/thymus-program"},
	{"Kyrylo will not join AION on-site; open to ad-hoc remote help", "aion/team-building"},
	{"Drew (8VC) to write up and send BA notes on med-device vs biotech capital markets", "aion/series-a-15m"},
	{"Send Grant the take-home problem set (RJ's mechanical-engineering problem)", "aion/team-building"},
	{"Connect AION with her immigration attorney and send the TN letter requirements", "aion/team-building"},
	{"Pursue the Skype-founder foundation grant-judging opportunity (get a formal invitation email stating selection criteria) and compile judging/publication options in the O1 doc for attorney review", "aion/team-building"},
	{"Re-engaged Butterfly sales thread to accelerate SDK negotiation", "aion/ultrasound-platform"},
	{"Run six-well GCaMP plates testing duty cycle, pulse repetition, and intensity matrix (under 1 watt)", "aion/ultrasound-platform"},
	{"Test finalized imaging settings and document them for future experiments", "aion/cell-reprogramming-wetlab"},
	{"Standardize on 3x3 high-speed binning for imaging/data analysis", "aion/cell-reprogramming-wetlab"},
	{"Executed research licensing agreement with the Academy of Japan for specialized cells", "aion/partnerships-advisory"},
	{"Hired McGill consultant to help stand up the model remotely", "aion/team-building"},
	{"Round structure undecided: SPV-with-carry vs. standard priced A", "aion/series-a-15m"},
	{"Explore whether AION fields can increase lymphocyte proliferation as a functional endpoint (with Milan Chheda's work)", "aion/thymus-program"},
	{"Study GCSF and comparable therapeutic clinical trial designs/endpoints as a predicate model", "aion/regulatory-strategy"},
	{"Evaluate iRepertoire for T/B-cell repertoire tracking", "aion/thymus-program"},
	{"Digest Hevolution's diligence templates and materials over the coming week", "aion/series-a-15m"},
	{"Write a 30-minute RFP-equivalent spec (incl. RPS claims) for a custom precise magnetic-field/microscope build", "aion/mechanism-validation"},
	{"Shop the custom field-system RFP to potential fabricators who could build it from the ground up", "aion/mechanism-validation"},
	{"Purchase the full panel of genetically encoded reporters (4 magnesium, chloride/pH, mito/lyso pH, redox via MTA)", "aion/cell-reprogramming-wetlab"},
	{"Order 25-magnesium isotope from China for the level-crossing-resonance experiments", "aion/mechanism-validation"},
	{"Deliver all genetically-encoded ion sensors via Lefty virus", "aion/cell-reprogramming-wetlab"},
	{"Run the force/math calculations on nanoparticle feasibility before buying any nanoparticles", "aion/mechanism-validation"},
	{"Run the field-application experiment for the ECM first (per Claude's suggestion)", "aion/mechanism-validation"},
	{"Use a 3D embedded ECM model rather than pseudo-2D", "aion/cell-reprogramming-wetlab"},
	{"Aggregate a list of researchers/publications on moving ions in/out of cells and cold-email them for background info", "aion/mechanism-validation"},
	{"Pivot from small-molecule interventions to EMF/field-based interventions", "aion/mechanism-validation"},
	{"Build the on-stage incubator rig for live-cell microscopy", "aion/cell-reprogramming-wetlab"},
	{"Pause magnetic + ultrasound program; replicate depolarization with ultrasound alone first", "aion/mechanism-validation"},
	{"Pursue a non-binding partnership with Lumius for customized 3D ultrasound hardware/software", "aion/partnerships-advisory"},
	{"Connect BA/RJ with Luminous (YC 3D-ultrasound startup) founders and assess partnership/acqui-hire", "aion/partnerships-advisory"},
	{"Put forward an ultrasound-specific design challenge to vet ultrasound candidates", "aion/team-building"},
	{"Prefer paid work-trials over full-time offers for high-caliber ultrasound candidates", "aion/team-building"},
	{"Keep the conversation going with ultrasound candidate Hyunwoo (potential trial-to-hire)", "aion/team-building"},
	{"Heye and Matthias to tag into ultrasound technical interviews", "aion/team-building"},
	{"Defer full freedom-to-operate analysis; do a focused preliminary IP landscape review with counsel instead", "aion/regulatory-strategy"},
	{"Take down the ultrasound engineer posting; keep biomedical/mechanical postings up as cheap hiring surface area", "aion/team-building"},
	{"Prioritize replicating the calcium-response ultrasound conditions and channel-inhibitor experiments (Piezo1, TRPV) to pin the mechanism before expanding the parameter matrix", "aion/mechanism-validation"},
	{"Replicate Hu 2019 magnetoacoustic hyperpolarization with mag+ultrasound extension", "aion/mechanism-validation"},
	{"Ready the magnetoacoustic hyperpolarization setup for testing by Dec 5", "aion/mechanism-validation"},
	{"Hold follow-up science scoping conversation (looping in Hannah) to narrow the Marugan-lab scope of work", "aion/thymus-program"},
	{"Skip formal Tufts advisory arrangement for Mike Levin; pursue co-publications with him instead over next 6-12 months", "aion/partnerships-advisory"},
	{"Recruited Siteman Cancer Center director onto AION scientific advisory board", "aion/partnerships-advisory"},
	{"Pursue funding Michael Levin's water-cognition startup in exchange for a Levin advisor role at AION", "aion/partnerships-advisory"},
	{"Talk to Michael Levin in March about the materials-perturbation project and an advisory relationship", "aion/partnerships-advisory"},
	{"Follow up with Dan, get intro to Luca Turin, and pursue Luca for the advisory board", "aion/partnerships-advisory"},
	{"Assemble a 3-4 person scientific advisory board (transplant immunology, neuro-oncology, wound healing/fundamentals)", "aion/partnerships-advisory"},
	{"Test all ~8 candidate field theories with one experiment each, keep the highest-effect-size ones and discard low-effect ones", "aion/mechanism-validation"},
	{"Follow up with Columbia on term sheet feedback for the collaboration", "aion/partnerships-advisory"},
	{"Ship final term sheet and scope of work to Columbia for the Murugan/Picard lab partnership", "aion/partnerships-advisory"},
	{"Columbia deal terms: ~2% royalty, co-owned IP with exclusive commercial license to AION, publication review rights, Martin as named PI supervised by Nirosha", "aion/partnerships-advisory"},
	{"Start reporter cell line transfections for the Murugan collaboration (pH, DiBAC, mito dyes) no later than the following week", "aion/cell-reprogramming-wetlab"},
	{"Refine the scope of work and narrow the budget for the Columbia sponsored research agreement", "aion/partnerships-advisory"},
	{"Run the Neurosha/Martin Picard proof-of-concept as a sponsored research agreement at Columbia", "aion/partnerships-advisory"},
	{"Review the Columbia/Martin industry-collaboration (CRO) contract Nirosha forwarded, ahead of TTO negotiation", "aion/partnerships-advisory"},
	{"Connect Benjamin with Columbia's Office of Research to negotiate the CRO arrangement", "aion/partnerships-advisory"},
	{"Fund a sponsored research collaboration in Nirosha's lab (salary + materials) in exchange for IP; ready to hire now", "aion/partnerships-advisory"},
	{"Hire Nirosha Murugan for the collaboration project (TN visa)", "aion/team-building"},
	{"6th-edition thymus regulatory strategy handed to consultant for review", "aion/regulatory-strategy"},
	{"Write TN visa employer support letter for Nirosha (target Friday)", "aion/team-building"},
	{"John DiPersio (Siteman director) joins scientific advisory board", "aion/partnerships-advisory"},
	{"Acquire materials and licensed IPSC lines to stand up the T-cell maturation model", "aion/cell-reprogramming-wetlab"},
	{"Answer Tucker's investor diligence questions (results, founder bios, SAB, target hires, affiliations, why-thymus)", "aion/series-a-15m"},
	{"Position the device as generic thymus/electromagnetic stimulation and avoid mechanism claims to the FDA", "aion/regulatory-strategy"},
	{"Flag the best MRI engineering talent encountered during market research for potential hiring", "aion/team-building"},
	{"Regulatory strategy: pursue general intended use claim with specific-indication fallback; sell read-only MRI before any write device", "aion/regulatory-strategy"},
	{"Send Joe Gleeson specific technical challenges/tasking from Yashiro to scope a computational MRI role", "aion/team-building"},
	{"Run a hiring sprint to bring on a couple more MRI engineers (ideally local, possibly Japan)", "aion/team-building"},
	{"Draft consumer-MRI capital-raise memo to share with Justin (and Evan Fisher)", "aion/series-a-15m"},
	{"Set up a follow-up MRI-focused call with Daisy/Eva (a16z), bringing RJ; Daisy to share Cube IO/Ezra MRI lessons", "aion/series-a-15m"},
	{"Send Jared a list of 5-10 medical-device companies (NovaCure, Hyperfine, Ladybug, etc.) that fit tool claims but pursued single indications", "aion/regulatory-strategy"},
	{"Form DETh (Directed Energy Therapeutics) collaboration with Tetrahedral and General Cybernetics", "aion/partnerships-advisory"},
	{"Investigate UAE fast-track device approval pathway (Justin's founder example: approved in 3 months, data feeds US submissions)", "aion/regulatory-strategy"},
	{"Order THP-1 cells for the collaboration", "aion/cell-reprogramming-wetlab"},
	{"Email Johnny and Tucker offering $250-500k at last round's price and set up a call with them plus Justin", "aion/series-a-15m"},
	{"St. Louis cell work targets fundamental biophysical control capabilities, not indication-specific proofs of concept", "aion/cell-reprogramming-wetlab"},
	{"Prioritize thymic epithelial cells (TECs) over thymocytes; treat calcium activation as a hazard", "aion/thymus-program"},
}
